# Generated by Django 4.0.7 on 2022-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_people_site_people_user_alter_formfield_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
