# Generated by Django 4.0.7 on 2022-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_people_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
