# Generated by Django 4.1.7 on 2023-04-16 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('base', '0010_sitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='image_ico',
            field=models.ForeignKey(help_text='Favicon', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
