# Generated by Django 4.2.6 on 2023-10-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_footertext_options_alter_people_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '---------'), ('m', 'Male'), ('f', 'Female')]),
        ),
    ]
