# Generated by Django 5.0.3 on 2024-03-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_speaker_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='gender',
            field=models.CharField(blank=True, choices=[('', '---------'), ('m', 'Männlich'), ('f', 'Weiblich')]),
        ),
    ]
