# Generated by Django 5.0.6 on 2024-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_speaker_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_number',
            field=models.IntegerField(blank=True, help_text='Number of items for first featured section', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_number',
            field=models.IntegerField(blank=True, help_text='Number of items for second featured section', null=True),
        ),
    ]
