# Generated by Django 6.0.8 on 2026-08-23 19:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_footertext_locale_alter_people_locale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoColumnsPage',
            fields=[
                ('standardpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.standardpage')),
                ('right_body', wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('video_block', 9), ('block_quote', 12), ('embed_block', 13), ('RawHTMLBlock', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'Select a aspect ratio'), ('1x1', '1x1'), ('4x3', '4x3'), ('16x9', '16x9'), ('21x9', '21x9')]}), 9: ('wagtail.blocks.StructBlock', [[('video_id', 7), ('ratio', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'e.g. Mary Berry', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 10), ('attribute_name', 11)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', 'icon': 'media', 'template': 'blocks/embed_block.html'}), 14: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Insert raw HTML e.g. <iframe>..</iframe>'})}, verbose_name='Right Page body')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.standardpage',),
        ),
    ]
