# Generated by Django 4.0.5 on 2022-07-17 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpagetag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date article published'),
        ),
    ]
