# Generated by Django 4.2.4 on 2023-08-09 10:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_eventindexpage_eventpage_eventspeakerrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.blocks.RichTextBlock(icon='pilcrow', template='blocks/paragraph_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('video_block', wagtail.blocks.StructBlock([('video_id', wagtail.blocks.CharBlock(required=True)), ('ratio', wagtail.blocks.ChoiceBlock(choices=[('', 'Select a aspect ratio'), ('1x1', '1x1'), ('4x3', '4x3'), ('16x9', '16x9'), ('21x9', '21x9')]))])), ('block_quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='media', template='blocks/embed_block.html')), ('RawHTMLBlock', wagtail.blocks.RawHTMLBlock(help_text='Insert raw HTML e.g. <iframe>..</iframe>'))], blank=True, use_json_field=True, verbose_name='page body'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date article published'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page', verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='additional_infos',
            field=wagtail.fields.RichTextField(blank=True, help_text="Write additional information's", null=True, verbose_name='additional infos'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 12, 41, 7, 224162, tzinfo=datetime.timezone.utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='registration_phone_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^(\\+\\d{1,3})?((-?\\d+)|(\\s?\\(\\d+\\)\\s?)|\\s?\\d+){1,9}$'), 'Enter a valid phone number i.e. +49 (531) 123456', 'invalid')], verbose_name='phone number for registration'),
        ),
    ]
