# Generated by Django 4.2.6 on 2023-10-20 10:15

import blogsite.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpage_body_alter_blogpage_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_date',
            field=models.DateTimeField(default=blogsite.blog.models._now_plus_120_minutes, verbose_name='end date'),
        ),
    ]
