# Generated by Django 5.0.3 on 2024-03-31 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_eventpage_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='with_registration_form',
            field=models.BooleanField(default=True, help_text='Displays a registration form.', verbose_name='with_registration_form'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='submit_time')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='telephone')),
                ('message', models.TextField(verbose_name='message')),
                ('to_email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='blog.eventpage')),
            ],
        ),
    ]
