# Generated by Django 5.0.6 on 2024-06-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogindexpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='highlight_introduction',
            field=models.BooleanField(default=False, verbose_name='highlight introduction'),
        ),
    ]
