# Generated by Django 6.0.5 on 2026-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_eventtemplate_eventpage_event_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='campai_event_id',
            field=models.CharField(blank=True, default=None, null=True, unique=True, verbose_name='campai Event ID'),
        ),
    ]
