# Generated by Django 4.1.3 on 2022-12-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('oidc', '0003_remove_userprofile_roles_rolegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolegroup',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oidc_group', to='auth.group'),
        ),
    ]
