# Generated by Django 4.1.3 on 2022-12-03 21:49

from django.db import migrations


def initial_data(apps, schema_editor):
    RoleGroup = apps.get_model("oidc.RoleGroup")
    Group = apps.get_model("auth.Group")

    moderators_group = Group.objects.get(name="Moderators")
    editors_group = Group.objects.get(name="Editors")

    # Create Moderators RoleGroup
    RoleGroup.objects.get_or_create(role="Moderators", defaults={'group': moderators_group, 'is_staff': False, "is_superuser": False})
    # Create Editors RoleGroup
    RoleGroup.objects.get_or_create(role="Editors", defaults={'group': editors_group, 'is_staff': False, "is_superuser": False})
    # Create Superusers RoleGroup
    RoleGroup.objects.get_or_create(role="Superuser", defaults={'is_staff': True, "is_superuser": True})


def remove_initial_data(apps, schema_editor):
    RoleGroup = apps.get_model("oidc.RoleGroup")
    RoleGroup.objects.filter(role__in=('Moderators', 'Editors', 'Superuser')).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('oidc', '0004_alter_rolegroup_group'),
    ]

    operations = [
        migrations.RunPython(initial_data, remove_initial_data),
    ]
